---
  - hosts: localhost
    gather_facts: True         
    vars:
        ingest_front_tunnel: 52.11.194.40:6379 
    tasks: 
    - include: tasks/setvars.yml  # sets {{ role_home_dir.stdout }} and hostname.stdout
    - include: tasks/shibboleth.yml app=registry  
    - include: tasks/monit.yml app=registry
    - include: tasks/stunnel.yml app=registry
    - name: clone registry source code
      git: repo=https://github.com/ucldc/avram dest=~/code/avram
    - name: install registry requirements
      pip3: requirements=~/code/avram/requirements.txt
   #- name: build avram environment
   #  command: ~/code/avram/init.sh creates=~/code/avram/bin/activate
    - name: copy .harvester-env to set REDIS_HOST
      copy:
        src: files/harvester-env
        dest: ~/.harvester-env
